/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import lombok.extern.slf4j.Slf4j;
import org.example.entity.Payment;
import org.example.entity.User;
import org.example.util.HibernateUtil;
import org.hibernate.Transaction;


@Slf4j
public class HibernateRunner {

    public static void main(String[] args) {
        try (var factory = HibernateUtil.buildSessionFactory()) {
            try (var session = factory.openSession()) {
                Transaction transaction = session.beginTransaction();
                User user = session.find(User.class, 1L);
                User user1 = session.find(User.class, 1L);
                transaction.commit();
            }
            try (var session = factory.openSession()) {
                Transaction transaction = session.beginTransaction();
                User user = session.find(User.class, 1L);
                User user1 = session.find(User.class, 1L);
                transaction.commit();
            }
        }
    }
}
